### PR TITLE
Update to the newest unit batch

### PR DESCRIPTION
**Pull request by jyc8**
Added Tobin, Delthea, Sonya, Gray, Leon, Saber, and Mathilda to DB.
Added their new skills to DB and code.
In DB, changed fireemblemheroes->skill->inheritrule from varchar(20) to varchar(50) to allow more tags.

Hopefully my exported sql works. Cancel Affinity is a pain in the...

### CODE REVIEW

**Comment by Andu2** [comment]
Hi, thanks for the contribution!

I'm not planning on keeping the version on my site updated anymore. If you want, you can host an updated version somewhere and I can link to it on my page. (I've already told this to several other people, though...)

**Comment by badgerbaj** [comment]
This is some nice clean code, I'd like to help keep this project going, but
if there are other interested devs, collaboration would be better than
several spin-offs.  Perhaps you could connect us all?

**Comment by Andu2** [comment]
I agree. Maybe I'll look into modifying the format so it can be used with GitHub Pages.

**Comment by Andu2** [comment]
I converted the database to a static JavaScript file so it works with GitHub Pages.  I've changed the database entries in @jyc8 's work to the new JSON format.

**Comment by ajhyndman** [comment]
@badgerbaj @jyc8 @Andu2 I'd be interested in collaborating to produce some kind of shared API server that serves stats for all Fire Emblem heroes.

I took a stab at building a common/shareable stat library, but maintaining versions across sites seems like a pain.

It would be better if there were a separate server that could give you:

* stats for heroes
* stats for skills
* heroes that come with skills
* can do the combat calculations and take skills into account

That would make it lots easier for devs to build their own tools and get guarantees that all of our sites will stay up to date with the latest heroes.

What I've got so far:

https://www.npmjs.com/package/fire-emblem-heroes-stats

**Comment by jyc8** [comment]
Hey @Andu2, the permissions are still locked for the public so I can only edit my fork. I'm not sure how to update the github page.

I'm not that familiar with php, sql, server etc. so I'll learn and help when I can, otherwise I'm just running a private version on my personal server haha.

**Comment by Andu2** [comment]
@jyc8 I haven't given anyone collaborator access yet. I feel like if I give anyone collaborator access, someone might come in just to fuck things up. But, if you keep helping out, I'll give you permission to push changes directly! (Just be careful, there's no dev environment other than your local copy...)

I ditched the PHP/MySQL approach because it wasn't compatible with GitHub Pages. So you don't have to learn that anymore, haha.

@ajhyndman I remember you showing me that. Now that we're using JSON data here, it seems preferable to use something like what you've set up. I'll take a look at it at some point.

I see that you have links to images on your server in the data. Does this mean you're capable of hosting the images for this calculator? My site used over 100GB of bandwidth the first month I had the calculator up even though I used low resolution images for the heroes, and 100GB is GitHub Pages' limit...

**Comment by ajhyndman** [comment]
@Andu2 I'm using [Cloudflare](https://www.cloudflare.com/) as a caching layer in front of my image server.  Bandwidth should be practically unlimited for free.  :+1:

**Comment by Andu2** [comment]
@ajhyndman Sweet :D

**Comment by badgerbaj** [comment]
I am mostly interested in doing a mobile app version of the site ( tie in
to the site via Web API and mobile likes JSON just fine for the data ), but
I could spruce up the web front end with some CSS magic as well.
Enhancement wise, I might look in to an auto "Optimal" button that will
show each character's "best" loadout as far as wins goes.

**Comment by ajhyndman** [comment]
@badgerbaj mobile apps are cool :+1:

Have you seen Google's latest mobile SDK, [**Flutter**](https://flutter.io/)?  I've been planning to tinker with it at some point.

**Comment by badgerbaj** [comment]
Yeah, I've looked in to Flutter.  I really like where they are going with
it.  I feel like Xamarin's biggest flaw is that they (Microsoft) hold the
least valuable platform ( Windows Phone ) and therefore Android/iOS support
will always be behind.  Google owning two of the platforms ( Android /
Fuchsia ) make only iOS secondary, which is a much more liveable solution.
However, its still a REALLY young platform.  I just don't think it is ready
yet.  Once it has its own dedicated IDE ( or way better integration into
Android Studio ), I'll begin using it.

**Pull request merged**
